name: test_micard_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: Flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data.json
    - assets/jopak/card.jpg
    - assets/jopak/profile.jpg
    - assets/juvi/card.jpg
    - assets/juvi/profile.jpg
    - assets/ace/
    - assets/drew/
    - assets/evane/
    - assets/ged/
    - assets/ivan/
    - assets/joshua/
    - assets/kalila/
    - assets/kenneth/
    - assets/michael/
    - assets/paul/

  fonts:
    - family: Inconsolata
      fonts:
        - asset: fonts/Inconsolata-Regular.ttf
